version: '3.8'

networks:
  cobra:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - ${PORT}:8080
    networks:
      - cobra
  cron:
    build:
      context: .
      dockerfile: Dockerfile
      target: cron
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - cobra